<?php

/**
 * @file
 * Webform plugin for Address element with Sierra Leone District.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_sierraleone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.webform_sierraleone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform plugin for Sierra Leone localization.') . '</p>';
      return $output;

    default:
  }
}
